[package]
name = "remotesync"
version = "0.1.0"
authors = ["Kevin Cotugno <kevin@kevincotugno.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
md5 = "0.7.0"
hex = "0.4.2"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
